### ISSUE TITLE
Commit in this repository that I did not make?

### ISSUE THREAD

**Issue by asm89** [keesschepers/concurrent-spider#102]
The initial commit in this repository is showing me as being the author. I have never contributed any code to the repository. Could you fix the history to reflect the actual author of the commit?

https://github.com/simgroep/concurrent-spider-bundle/commit/cb4f1071c06cea53ab9757a35e061c75ac1a4ff9

**Comment by lkalinka** [comment]
Your commit was replaced, with "correct" Author values

Cheers!

**Comment by asm89** [comment]
Thanks for the quick reply @lkalinka. 👍 

Any chance we can figure out how to purge the actual commit I linked as well? I think we might have to contact GH support.

**Comment by lkalinka** [comment]
i tried to remove that . It is not shown on git show , or in git log ... but its shown in github only so it might be a github issue related to first commit. So we might write some email to github about this
