### ISSUE TITLE
vdb/php-spider composer dependies problem

### ISSUE THREAD

**Issue by RomainMarecat** [keesschepers/concurrent-spider#87]
I can't install the bundle due to symfony 
- vdb/php-spider dev-master requires symfony/dom-crawler ^3.0.0 -> satisfiable by symfony/symfony[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4], symfony/dom-crawler[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4].
  - don't install symfony/dom-crawler v3.0.0|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.1|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.2|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.3|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.4|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.5|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.6|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.7|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.8|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.0.9|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.1.0|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.1.1|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.1.2|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.1.3|don't install symfony/symfony v2.4.0
  - don't install symfony/dom-crawler v3.1.4|don't install symfony/symfony v2.4.0
  - simgroep/concurrent-spider-bundle dev-master requires symfony/symfony >=2.4,<3 -> satisfiable by symfony/symfony[v2.8.11, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
  - Conclusion: don't install symfony/symfony v2.4.1

**Comment by othillo** [comment]
@RomainMarecat this commit https://github.com/simgroep/concurrent-spider-bundle/pull/115/commits/d68c98834b8d0ba9cf56bf6644f313c142b463d7 may have fixed this issue. Closing this for now.
